name: Telegram Bot Scheduler

on:
  schedule:
    - cron: '0 13 * * *'  # 8:00 AM Lima (UTC-5)
    - cron: '0 15 * * *'  # 10:00 AM Lima (UTC-5)
    - cron: '45 17 * * *' # 12:45 PM Lima (UTC-5)
  workflow_dispatch:  # Esto permite ejecutarlo manualmente

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: pip install requests pytz
    - name: Check script existence
      run: |
        if [ -f "coach.py" ]; then
          echo "Script coach.py found"
        else
          echo "Error: coach.py not found"
          exit 1
        fi
    - name: Send Telegram message
      env:
        TELEGRAM_BOT_TOKEN: '7920295504:AAFc4evIRk4jl7ekBxgfm2eX5E6fTYUclNE'
        TELEGRAM_CHAT_ID: '5518550492'
      run: |
        echo "Starting Telegram bot execution"
        python coach.py || echo "Script failed with exit code $?"
