name: Telegram Bot Scheduler

on:
  schedule:
    - cron: '0 8 * * *'   # 8:00 AM UTC
    - cron: '0 10 * * *'  # 10:00 AM UTC  
    - cron: '45 12 * * *' # 12:45 PM UTC

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: pip install requests
    - name: Send Telegram message
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python bot_telegram.py
